"""UI constants following Apple Design System from DESIGN.md"""

# SPACING SYSTEM (8px base unit)
SPACING_TINY = 2
SPACING_XXSMALL = 4
SPACING_XSMALL = 6
SPACING_SMALL = 8
SPACING_MEDIUM = 12
SPACING_LARGE = 20
SPACING_XLARGE = 28

# DIVIDER WIDTHS (standardized, intentionally restrained)
DIVIDER_SHORT = 8
DIVIDER_MEDIUM = 12
DIVIDER_LONG = 16

# METER BAR WIDTHS
METER_COMPACT = 6
METER_STANDARD = 8
METER_WIDE = 10

# ICONS (minimal Apple style)
ICON_SUCCESS = "✓"
ICON_ERROR = "✗"
ICON_WARNING = "⚠"
ICON_INFO = "•"
ICON_LOADING = "○"

# SPINNER FRAMES (subtle, single-dot motion)
SPINNER_FRAMES = ("○", "◔", "◑", "◕")

# STATUS INDICATORS
STATUS_ACTIVE = "✓"
STATUS_INACTIVE = "✗"
STATUS_PENDING = "○"

# MESSAGE PREFIXES (minimal)
PREFIX_SUCCESS = "✓"
PREFIX_ERROR = "✗"
PREFIX_INFO = "•"

# ABYSS/COMBAT ICONS (minimal)
ICON_DAMAGE = "•"  # Simplified from ⚔
ICON_SHIELD = "○"
ICON_KILL = "✗"
ICON_ENERGY = "•"  # Simplified from ✨
